### ISSUE TITLE
Add option for basic auth that sets header with token

### ISSUE THREAD

**Issue by dpikt** [LaunchPadLab/lp-requests#41]
https://en.wikipedia.org/wiki/Basic_access_authentication#Client_side

**Comment by rkillackey** [comment]
@dpikt Should we assume that the token is already a base64 encoded username/pass combo?

**Comment by dpikt** [comment]
@rkillackey I was envisioning that it would do more work for you, provided username and password arguments.

`{ basicAuthUser: 'david', basicAuthPass: 'secret' }`

**Comment by dpikt** [comment]
@rkillackey actually, let's copy what axios does:
https://stackoverflow.com/a/44239543

**Comment by rkillackey** [comment]
Okay, yeah that's kind of what I started doing just with a different key
