### ISSUE TITLE
204 Response Should Not Expect Body

### ISSUE THREAD

**Issue by mwislek** [LaunchPadLab/lp-requests#90]
A successful response of 204 (No Content) should not expect a body. The `http::getResponseBody` method should be updated with with condition so that no exception is generated.

**Comment by chawes13** [comment]
@mwislek Did this come up while working on a project? What's the priority?

**Comment by mwislek** [comment]
Yes, while working on Isaksen. It’s not a huge priority. Without this fix we get exceptions but there doesn’t seem to be any issue with the app itself, i.e., it is able to recover from those exceptions successfully.

From: Conor ***@***.***>
Reply-To: LaunchPadLab/lp-requests ***@***.***>
Date: Tuesday, April 13, 2021 at 8:20 PM
To: LaunchPadLab/lp-requests ***@***.***>
Cc: Mike Wislek ***@***.***>, Mention ***@***.***>
Subject: Re: [LaunchPadLab/lp-requests] 204 Response Should Not Expect Body (#90)


@mwislek<https://github.com/mwislek> Did this come up while working on a project? What's the priority?
